### ISSUE TITLE
URP Support

### ISSUE THREAD

**Issue by otdavies** [otdavies/UnityChromakey#2]
URP support has been requested. The current the shader is only setup to support HDRP. 

**Definition of done:** 
URP branch with similar features to HDRP.

**Comment by RyBK** [comment]
Has there been any development on this enhancement for URP support?

**Comment by otdavies** [comment]
Unfortunately not recently, no. I haven't played with the newer renditions of URP. I'll re-evaluate this when I have some free time. It shouldn't be too difficult and with a little knowledge of shaderlab / URP you could likely port it.

**Comment by ivoras** [comment]
bump :)

**Comment by otdavies** [comment]
Just tested this, it works out of the gate apparently, go wild.

**Comment by otdavies** [comment]
URP vvv

![image](https://user-images.githubusercontent.com/3145170/143796306-7b6bcdab-b34f-42d6-8ec5-7c56285f6b08.png)
