### ISSUE TITLE
Adding effects on top of keyed videos

### ISSUE THREAD

**Issue by ddyuldashev** [otdavies/UnityChromakey#4]
How can we add shader graph effects on top of keyed videos? Should we translate this code into a shader graph and then combine effects? Let's say, for instance, that I want to add a holographic effect after applying the chroma key shader. How should I approach this? Thanks.

**Comment by otdavies** [comment]
Hey there, sorry for the late response - You could take the implementation (and articles from the bottom of the readme) and reimplement this in shader graph if you'd like. In theory you could add this shader as a final or initial pass in a shader, but I am honestly not sure how well shader graph plays with those kinds of setups.

**Comment by ddyuldashev** [comment]
Thanks for replying. Yes, the implementation is not straightforward.
